spring.application.name=backend

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=baophuccqt
spring.datasource.password=baophuccqt